Repository gdsclpu/OpenWorldAPI, pull requests merged in 2022-10, with the labels that each got.

#96 Added all 50 States and Capitals of United States of America
  data/countries.json
  data/countries/us.json
  data/countries/usa.json
  data/makecountries.js
Labels: hacktoberfest-accepted

#100 Added data about Japan, its capital, districts, and cities
  data/countries/japan.json
Labels: hacktoberfest-accepted

#106 Feature/updated readme
  README.md
  controllers/cities.js
  controllers/district.js
  controllers/states.js
  data/actions.js
  public/img/apidocs.png
Labels: hacktoberfest-accepted

#103 Added Bangladesh's states and respective districts
  data/countries/bangladesh.json
Labels: hacktoberfest-accepted

#101 Added Pakistan's states and district data
  data/countries/pakistan.json
  data/structure.json
Labels: hacktoberfest-accepted

#99 Updated Monaco.json
  data/countries/monaco.json
Labels: hacktoberfest-accepted

#107 Added the rest of districts and cities of Japan
  data/countries/japan.json
Labels: hacktoberfest-accepted

#108 Added Aruba's district and state list
  data/countries/aruba.json
Labels: hacktoberfest, hacktoberfest-accepted

#110 Added Cambodia's state and district data
  data/countries/cambodia.json
Labels: hacktoberfest-accepted

#112 Feature/logic for other countries
  .vscode/settings.json
  controllers/cities.js
  controllers/district.js
  controllers/states.js
  data/actions.js
  data/countries/brazil.json
Labels: hacktoberfest-accepted

#115 Added Algeria's list of provinces and district
  data/countries/algeria.json
Labels: hacktoberfest-accepted

#117 Added currency, Capital and Districts of Mauritius
  data/countries/mauritius.json
Labels: hacktoberfest-accepted

#118 Added all the states and capitals of Afghanistan
  data/countries/afghanistan.json
Labels: hacktoberfest-accepted

#119 Added all districts of Badakhshan, Badghis, and Baghlan.
  data/countries/afghanistan.json
Labels: hacktoberfest-accepted

#121 Added all states Of Argentina
  data/countries/argentina.json
Labels: hacktoberfest-accepted

#124 Added all cities under shanghai Baoshan
  data/countries/china.json
Labels: hacktoberfest-accepted

#123 bahamas data added
  data/countries/bahamas.json
Labels: hacktoberfest-accepted

#125 Added all districts under Zhejiang China
  data/countries/china.json
Labels: hacktoberfest-accepted

#127 Added all districts under TianJin China
  data/countries/china.json
Labels: hacktoberfest-accepted

#128 Added all districts under Qinghai China
  data/countries/china.json
Labels: hacktoberfest-accepted

#135 updated Australia's details
  data/countries/australia.json
Labels: hacktoberfest-accepted

#136 updated Kuwait's database
  data/countries/kuwait.json
Labels: hacktoberfest-accepted

#137 updated malta.json
  data/countries/malta.json
Labels: hacktoberfest

#140 added Belarus details
  data/countries/belarus.json
Labels: hacktoberfest-accepted

#144 Added Districts for Bamyan and Daykundi
  data/.DS_Store
  data/countries/aab.json
  data/countries/afghanistan.json
Labels: hacktoberfest-accepted

#150 zimbabwe data added
  data/countries/zimbabwe.json
Labels: hacktoberfest-accepted

#149 bhutan data updated
  data/countries/bhutan.json
Labels: hacktoberfest-accepted

#148 Nauru Data updated
  data/countries/nauru.json
Labels: hacktoberfest-accepted

#152 Added Andorra Data
  data/countries/andorra.json
  data/countries/angola.json
Labels: hacktoberfest-accepted

#156 Added Anguilla Details
  data/countries/anguilla.json
Labels: hacktoberfest-accepted

#158 Added Antarctica Detalis
  data/countries/antarctica.json
Labels: hacktoberfest-accepted

#160 Added Antarctica
  data/countries/albania.json
Labels: hacktoberfest-accepted

#162 Added Austria Details
  data/countries/austria.json
Labels: hacktoberfest-accepted

#164 Yaswanthb13
  data/countries/bangladesh.json
Labels: hacktoberfest-accepted

#168 Updated bah.json
  data/countries/bah.json
Labels: hacktoberfest-accepted

#170 Update bahrain.json
  data/countries/bahrain.json
Labels: hacktoberfest-accepted

#172 Update barbados.json
  data/countries/barbados.json
Labels: hacktoberfest, hacktoberfest-accepted

#174 Update Brunei Darussalam Data
  data/countries/bd.json
Labels: hacktoberfest-accepted

#175 Added Parishes and dependencies of Antigua and Barbuda in aab JSON
  data/countries.json
  data/countries/aab.json
Labels: hacktoberfest-accepted

#182 Update belize.json
  data/countries/belize.json
Labels: hacktoberfest-accepted

#184 Create bolivia.json
  data/countries/bolivia.json
Labels: hacktoberfest-accepted
